server:
  port: 8888
spring:
  application:
    name: studentpool_config_server
  profiles:
    active:
    - git
    - native
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/shiva508/studentpool_config
          repos:
            dev-studentpool_preparation:
              pattern: studentpool_preparation*/*
              uri: https://github.com/shiva508/studentpool_config
              search-paths:
                - spring-cloud-config-server-setup/{application}/{profile}
            
            dev-studentpool_notes:
              pattern: studentpool_notes*/*
              uri: https://github.com/shiva508/studentpool_config
              search-paths:
                - spring-cloud-config-server-setup/{application}/{profile}
management:
  endpoints:
    web:
      exposure:
        include: "*"