server:
  port: 8888
spring:
  application:
    name: studentpool_config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shiva508/studentpool_config
          username: shiva508
          password: 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
          repos:
            dev-studentpool_preparation:
              pattern: studentpool_preparation*/*
              uri: https://github.com/shiva508/studentpool_config
              search-paths:
                - spring-cloud-config-server-setup/{application}/{profile}
              
                